name: Push

on: push

jobs:
  test:
    name: Lint, build, and test on node 14.x and ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Lint codebase
        run: yarn lint
      - name: Build codebase
        run: yarn build
      - name: Test codebase
        run: yarn test --coverage
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
